# Works with Jekyll 3.2.1

# Setup
title:               hyunkim.lawyer
tagline:             '오답은 있지만 정답은 없다. 언제나 더 나은 답이 있다.'
description:         '미국변호사 김변의 노트'
url:                 'http://hyunkim.lawyer'
baseurl:             ''
future: false

# About/contact
author:
  name:              Hyun Kim
  url:               http://hyunkim.lawyer
  email:             hyunkim@hyunkim.lawyer

# Permalinks

# permalink: pretty
permalink: /blog/:year/:month/:title.html
color-scheme: blue

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true
  how:
    output: true
    permalink: /how/:title.html
  laws:
    output: true
    permalink: /laws/:title.html
  dictionary:
    output: true
    permalink: /dictionary/:title.html
  categories:
    output: true
    permalink: /categories/:title.html
  codes:
    output: true
    permalink: /codes/:title.html
  living:
    output: true
    permalink: /living/:title.html
    
# Markdown specs
markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Custom vars
version:             0.0.1

# Exclusions from the final site
exclude: [s3_website.yml, optional, vendor, misc, temps]

# Gems
gems: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_templates: "{{references}}"
  relative: "/ed/bibliography.html"
  replace_strings: true
  join_strings: true
  use_raw_bibtex_entry: false
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"